#  Análisis de datasets de Hungtington

Consideramos los datasets: 

*   INVESTIGATION OF DIFFERENTIALLY EXPRESSED GENE RELATED TO HUNTINGTON’S
DISEASE USING GENETIC ALGORITHM (referencia apuntes overleaf i.13)
*   Identification of Biclusters in Huntington’s Disease Dataset Using a New Variant of Grey Wolf
Optimizer (referencia apuntes overleaf i.15)

`GSE3790` y `GSE26927`

> **Contexto GSE3790:** El dataset se obtuvo del organismo *homo sapiens*. El tipo de experimento fue: *expression profiling by array*. El resumen: *Post mortem human brain tissue comparison between HD patients and controls from 3 brain regions - cerebellum, frontal cortex [BA4, BA9] and caudate nucleus. Gene expression analysed using linear models from LIMMA package in Bioconductor suite*. El diseño: *Large sample sizes were used to examine brain tissue gene expression at various stages of HD pathology. Three brain regions were profiled, compared and analysed for differential gene expression. The broad aim was to capture early stage gene expression changes in HD brains*.

## Primero extraemos archivos .gz

Así obtenemos los archivos .cel necesarios para hacer el análisis de datos.

Esta extensión está asociada con experimentos de microarrays de Affymetrix y contienen valores sin procesar de cada prueba del microarray.

Affymetrix es una empresa, y de ahí el nombre de la plataforma para procesamiento de muestras provenientes de RNA para análisis de expresión génica diferencial.

Utilizaremos el módulo [biopython](https://biopython.org/docs/1.75/api/Bio.Affy.CelFile.html) para trabajar con archivos con formato .cel

In [1]:
import os
import gzip
import zipfile
import shutil
dir_ = '../Data/GSE3790/'


In [19]:
# Esta celda solo se corre una vez para descomprimir los archivos .gz
for item in os.listdir(dir_):
    name = item.split('.gz')[0]
    print(name)
    # zip = zipfile.ZipFile(f'{dir}{item}')
    # zip.extractall()
    # zip.close()
    with gzip.open(f'{dir_}{item}', 'rb') as f_in:
        with open(f'{dir_}{name}', 'wb') as f_out:
            shutil.copyfileobj(f_in, f_out)

GSM86787.cel
GSM86788.cel
GSM86789.cel
GSM86790.cel
GSM86791.cel
GSM86792.cel
GSM86793.cel
GSM86794.cel
GSM86795.cel
GSM86796.cel
GSM86797.cel
GSM86798.cel
GSM86799.cel
GSM86800.cel
GSM86801.cel
GSM86802.cel
GSM86803.cel
GSM86804.cel
GSM86805.cel
GSM86806.cel
GSM86807.cel
GSM86808.cel
GSM86809.cel
GSM86810.cel
GSM86811.cel
GSM86812.cel
GSM86813.cel
GSM86814.cel
GSM86815.cel
GSM86816.cel
GSM86817.cel
GSM86818.cel
GSM86819.cel
GSM86820.cel
GSM86821.cel
GSM86822.cel
GSM86823.cel
GSM86824.cel
GSM86825.cel
GSM86826.cel
GSM86827.cel
GSM86828.cel
GSM86829.cel
GSM86830.cel
GSM86831.cel
GSM86832.cel
GSM86833.cel
GSM86834.cel
GSM86835.cel
GSM86836.cel
GSM86837.cel
GSM86838.cel
GSM86839.cel
GSM86840.cel
GSM86841.cel
GSM86842.cel
GSM86843.cel
GSM86844.cel
GSM86845.cel
GSM86846.cel
GSM86847.cel
GSM86848.cel
GSM86849.cel
GSM86850.cel
GSM86851.cel
GSM86852.cel
GSM86853.cel
GSM86854.cel
GSM86855.cel
GSM86856.cel
GSM86857.cel
GSM86858.cel
GSM86859.cel
GSM86860.cel
GSM86861.cel
GSM86862.cel
GSM86863.cel

In [2]:
from Bio.Affy import CelFile
import pandas as pd

In [4]:
def cel_read(file):
    file = f'../Data/GSE3790/{file}'
    print(file)
    with open(file,'r') as handle:
        cel_data = CelFile.read(handle) #el parametro version depende para ciertos paquetes
#         cel_values = cel_data.header.data tambien se puede pedir los atributos cel_data.ncols, cel_data.nrows, cel_data.stdevs,cel_data.npix, intensities
#         print(cel_values)
        return cel_data

In [5]:
ejemplo = cel_read('GSM86787.cel')

../Data/GSE3790/GSM86787.cel


In [6]:
print(f'''Número de filas: {ejemplo.nrows}\n
Número de columns: {ejemplo.ncols}\n
Intensidades: {ejemplo.intensities}\n
Desviacion estandar: {ejemplo.stdevs}\n
Número de pixeles: {ejemplo.npix}\n
Version del Affymatrix: {ejemplo.version}\n''')

Número de filas: 712

Número de columns: 712

Intensidades: [[  217.8 11579.3   223.  ... 13801.8   248.3 14241. ]
 [12470.    218.8 11507.8 ...   212.8 13649.    227.8]
 [  275.3 11250.8   220.8 ... 12645.8   246.3 13643.3]
 ...
 [12404.3   217.  11651.  ...   185.  10700.8   146. ]
 [  238.8 11953.5   237.3 ... 11242.5   186.3 11238.8]
 [13141.    235.3 12226.5 ...   175.  11644.3   129.8]]

Desviacion estandar: [[  54.2 1712.6   49.7 ... 2000.7   41.2 2039.2]
 [1651.1   59.2 1424.4 ...   32.2 1871.    41.4]
 [ 141.6 2036.6  117.6 ... 1874.4   52.2 1994. ]
 ...
 [1920.    38.5 1756.9 ...   38.5 1037.3   20.5]
 [  53.9 1740.7   38.  ... 1162.    20.9 1242.1]
 [1858.7   48.5 1738.7 ...   26.1 1178.9   16.9]]

Número de pixeles: [[16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 ...
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]
 [16 16 16 ... 16 16 16]]

Version del Affymatrix: 3



In [8]:
print(f"intensities es : {type(ejemplo.intensities)}")

intensities es : <class 'numpy.ndarray'>


In [7]:
#Verificamos el tamaño de cada archivo 
for file in os.listdir(dir_):
    c = cel_read(file)
    print(f"Rows: {c.nrows}, Cols: {c.ncols}")

../Data/GSE3790/GSM86787.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86788.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86789.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86790.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86791.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86792.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86793.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86794.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86795.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86796.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86797.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86798.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86799.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86800.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86801.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86802.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86803.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86804.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86805.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86806.cel
Rows: 712, Cols: 712


Rows: 712, Cols: 712
../Data/GSE3790/GSM86952.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86953.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86954.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86955.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86956.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86957.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86958.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86959.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86960.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86961.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86962.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86963.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86964.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86965.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86966.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86967.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86968.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86969.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86970.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM86971.cel


Rows: 712, Cols: 712
../Data/GSE3790/GSM87116.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87117.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87118.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87119.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87120.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87121.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87122.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87123.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87124.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87125.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87126.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87127.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87128.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87129.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87130.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87131.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87132.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87133.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87134.cel
Rows: 712, Cols: 712
../Data/GSE3790/GSM87135.cel


In [44]:
def cel_to_df(file):
    file = f'../Data/GSE3790/{file}'
    print(file)
    with open(file,'r') as handle:
        cel_data = CelFile.read(handle)
        df = pd.DataFrame({'intensities':cel_data.intensities,
                          'stdevs':cel_data.stdevs,
                          'npix':cel_data.npix},
                          index=range(len(cel_data.intensities)))
        return df

In [45]:
ejemplo_df = cel_to_df('GSM86787.cel')

../Data/GSE3790/GSM86787.cel


Exception: Data must be 1-dimensional